version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      safe-development-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
  - package-ecosystem: docker
    directory: /apps/web
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /apps/cms
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /apps/commerce
    schedule:
      interval: weekly
